version: '3.9'

include:
  - "docker-compose-network.yaml"

services:
  dev-app-production:
    container_name: api.ze-burger-production.dev
    env_file: .env
    build:
      dockerfile: ./infra/docker/local/Dockerfile
      context: ./
    volumes:
      - .:/app
    ports:
      - 8082:8082
    networks:
      - dev-networks

  dev-app-production-order-created-worker:
    container_name: worker.ze-burger-production-order-created.dev
    env_file: .env
    command: >
      sh -c "go run cmd/worker/order_created_worker/main.go"
    build:
      dockerfile: ./infra/docker/local/Dockerfile
      context: ./
    volumes:
      - .:/app
    networks:
      - dev-networks

  dev-app-production-payment-confirmed-worker:
    container_name: worker.ze-burger-production-payment-confirmed.dev
    env_file: .env
    command: >
      sh -c "go run cmd/worker/payment_confirmed_worker/main.go"
    build:
      dockerfile: ./infra/docker/local/Dockerfile
      context: ./
    volumes:
      - .:/app
    networks:
      - dev-networks
