version: '3.9'

include:
  - "docker-compose-network.yaml"

services:
  dev-app-production:
    container_name: api.ze-burger-production.dev
    env_file: .env
    build:
      dockerfile: ./infra/docker/local/Dockerfile
      context: ./
    volumes:
      - .:/app
    ports:
      - 8082:8082
    networks:
      - dev-networks
