definitions:
  input.StatusProductionDto:
    properties:
      status:
        type: string
    required:
    - status
    type: object
  swagger.InternalServerErrorResponse:
    properties:
      data: {}
      error:
        example: Internal server error
        type: string
    type: object
  swagger.ResourceNotFoundResponse:
    properties:
      data: {}
      error:
        example: Resource not found
        type: string
    type: object
info:
  contact: {}
paths:
  /productions:
    get:
      description: Find all production by id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/swagger.ResourceNotFoundResponse'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/swagger.InternalServerErrorResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Find all production
      tags:
      - Production
  /productions/{id}:
    patch:
      description: Update production by id
      parameters:
      - description: Production ID
        in: path
        name: id
        required: true
        type: string
      - description: Production status
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/input.StatusProductionDto'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/swagger.ResourceNotFoundResponse'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/swagger.InternalServerErrorResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Update production
      tags:
      - Production
swagger: "2.0"
