apiVersion: apps/v1
kind: Deployment
metadata:
  name: ze-burguer-production-order-worker
spec:
  selector:
    matchLabels:
      app:  ze-burguer-production-order-worker
  template:
    metadata:
      labels:
        app: ze-burguer-production-order-worker
    spec:
      containers:
        - name: ze-burguer-production-order-worker
          image: marcosilva/ze_burguer_production:latest
          command:
            - /cmd/worker/order_created_worker/main
          resources:
            requests:
              cpu: "30m"
            limits:
              cpu: "30m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ze-burguer-production-payment-worker
spec:
  selector:
    matchLabels:
      app:  ze-burguer-production-payment-worker
  template:
    metadata:
      labels:
        app: ze-burguer-production-payment-worker
    spec:
      containers:
        - name: ze-burguer-production-payment-worker
          image: marcosilva/ze_burguer_production:latest
          command:
            - /cmd/worker/payment_confirmed_worker/main
          resources:
            requests:
              cpu: "30m"
            limits:
              cpu: "30m"